apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: mycontainer
        image: docker.io/medamine97/love2shop_backend:latest
        ports:
        - containerPort: 8443
        resources:
          limits:
            cpu: "1"
            memory: "512Mi"
          requests:
            cpu: "100m"
            memory: "256Mi"
        env:
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:mysql://database-love2shop-service.love2shop.svc.cluster.local:3306/love2shop?createDatabaseIfNotExist=true"
        - name: SPRING_DATASOURCE_USERNAME
          value: "root"
        - name: SPRING_DATASOURCE_PASSWORD
          value: "rootpassword"
        - name: SPRING_SQL_INIT_MODE
          value: "always"
        - name: SPRING_JPA_HIBERNATE_DDL_AUTO
          value: "update"