apiVersion: v1
kind: Service
metadata:
  name: database-love2shop-service
  labels:
    app: database
spec:
  selector:
    app: database
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306 #mysql port
  type: ClusterIP